name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"  # 每5天运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2
        
      - name: 安装 Playwright 所需依赖
        run: |
          npx playwright install-deps

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 安装python脚本所需依赖
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiofiles requests

      - name: 安装 Playwright 浏览器
        run: |
          playwright install firefox
          
      - name: 创建WARP网络
        uses: fscarmen/warp-on-actions@v1.3
        with:
           stack: dual        # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
           mode: client    # Optional. Support [ wireguard, client ]. Default is wireguard.

      - name: 运行自动化登录脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOST: ${{ secrets.WEBHOST }}
        run: |
          python login_script.py
